"use client";
import React from "react";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
import { usePathname } from "next/navigation";
import Link from "next/link";
import { ErrorWrapper } from "./error-wrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} h-screen`}>
        <header className="bg-gray-200 h-12 flex items-center px-4 font-semibold text-black h-[5vh]">
          Next.js First Project
          <Link href="/" className="ml-4 text-sm font-normal">
            {pathname.split("/").filter(Boolean).length > 0 ? "Home" : ""}
          </Link>
        </header>
        <ErrorWrapper>{children}</ErrorWrapper>
        {/* <main className="h-[90vh] flex-1 p-4 overflow-auto"><ErrorWrapper>{children}</ErrorWrapper></main> */}
        <footer className="bg-gray-200 h-12 flex items-center px-4 font-semibold text-black h-[5vh]">
          Copyright © 2025
        </footer>
      </body>
    </html>
  );
}
